post_install() {
  cd /opt/openoffice/program
  ./unopkg add --shared
  [ -x /usr/bin/update-desktop-database ] && /usr/bin/update-desktop-database > /dev/null 2>&1
}

pre_upgrade() {
  /bin/true
}

post_upgrade() {
  post_install $1 
}

pre_remove () {
  rm -r /opt/openoffice/share/{uno_packages,registry} 
}

post_remove () {
  [ -x /usr/bin/update-desktop-database ] && /usr/bin/update-desktop-database > /dev/null 2>&1
}

op=$1
shift

$op $*
