/*  mesg_ru.h
 *
 *  copyright (c) 2000-2003 SeaD
 *  see GPL for copying info
 *
 */

#ifndef _MESG_H
#define _MESG_H 1

#define CHNL_OUT        "[%s] недостаточно каналов %s\n"
#define CHNL_JOIN       "[%s] %s вошел на канал %s.\n"
#define CHNL_LEAVE      "[%s] %s покинул канал %s.\n"
#define CHNL_JOINP      "[%s] %s вошел в приват.\n"
#define CHNL_LEAVEP     "[%s] %s покинул приват.\n"

#define CMND_HQUIT      "[%s] %s(%s,%s): выход %s.\n"
#define CMND_HHELP      "[%s] %s(%s,%s) [<command>]: подсказка по команде.\n"
#define CMND_HVERSION   "[%s] %s(%s): показать версию.\n"
#define CMND_HSTATUS    "[%s] %s(%s): показать текущий статус.\n"
#define CMND_HKEYS      "[%s] %s(%s): показать используемые клавиши.\n"
#define CMND_HVERBOSE   "[%s] %s(%s): комментарии.\n"
#define CMND_HCLEAR     "[%s] %s(%s): очистить историю команд и экрана.\n"
#define CMND_HSHELL     "[%s] %s [<command>]: команда шелла.\n"
#define CMND_HLOAD      "[%s] %s [<filename>]: загрузить конфигурацию.\n"
#define CMND_HSAVE      "[%s] %s [<filename>]: сохранить конфигурацию.\n"
#define CMND_HANSWER    "[%s] %s(%s) [<new autoanswer>]: показать/сменить автоответ.\n"
#define CMND_HGENDER    "[%s] %s(%s): сменить пол.\n"
#define CMND_HMY        "[%s] %s: сменить режим звуков.\n"
#define CMND_HFAVORITE  "[%s] %s(%s) [<nick1> <nick2> ...]: показать/выделить/невыделить ник(и).\n"
#define CMND_HIGNORE    "[%s] %s(%s) [<nick1> <nick2> ...]: показать/игнорировать/неигнорировать ник(и).\n"
#define CMND_HBAN       "[%s] %s [<nick1> <nick2> ...]: показать/игнорировать/неигнорировать адрес(а).\n"
#define CMND_HJOIN      "[%s] %s(%s) <channel>: войти на канал.\n"
#define CMND_HLEAVE     "[%s] %s(%s) [<channel>]: покинуть канал.\n"
#define CMND_HNICK      "[%s] %s(%s) <newnick>: сменить ник.\n"
#define CMND_HMESG      "[%s] %s(%s,%s) <nick> <mesg>: послать сообщение нику.\n"
#define CMND_HMASS      "[%s] %s <mesg>: послать массовое сообщение.\n"
#define CMND_HEXEC      "[%s] %s <nick> <command>: исполнить команду.\n"
#define CMND_HME        "[%s] %s [<action>]: показать действие.\n"
#define CMND_HTOPIC     "[%s] %s(%s) [<newtopic>]: показать/сменить топик.\n"
#define CMND_HADD       "[%s] %s [<addtopic>]: добавить к топику.\n"
#define CMND_HMODE      "[%s] %s(%s) [<0-4>]: сменить режим.\n"
#define CMND_HNORMAL    "[%s] %s(%s): сменить режим на Нормальный.\n"
#define CMND_HDND       "[%s] %s(%s) [<new autoanswer>]: сменить режим на Не Беспокоить.\n"
#define CMND_HAWAY      "[%s] %s(%s) [<new autoanswer>]: сменить режим на Ушел.\n"
#define CMND_HOFF       "[%s] %s(%s) [<new autoanswer>]: сменить режим на Отключен.\n"
#define CMND_HINFO      "[%s] %s(%s,%s) [<nick1> <nick2> ...]: получить инфо на ник(и).\n"
#define CMND_HBEEP      "[%s] %s(%s) [<nick1> <nick2> ...]: послать звук на ник(и).\n"
#define CMND_HTALK      "[%s] %s(%s,%s) <nick>: вызвать ник в приват.\n"
#define CMND_HHERE      "[%s] %s: кто здесь.\n"
#define CMND_HACTIVE    "[%s] %s: сменить активность.\n"
#define CMND_HCOMMANDS  "[%s] доступные команды:\n"
#define CMND_HKEYWORK   "[%s] используемые клавиши:\n"
#define CMND_HKEY1      "F1-8 - переключиться на канал\n"
#define CMND_HKEY2      "^O or TAB - следующий канал\n"
#define CMND_HKEY3      "^D - выйти из чата\n"
#define CMND_HKEY4      "^A - сменить активность\n"
#define CMND_HKEY5      "^K - перевернуть список ников\n"
#define CMND_HKEY6      "^L or INS - обновить список ников\n"
#define CMND_HKEY7      "^R - обновить экран\n"
#define CMND_HKEY8      "^T - перейти вверх экрана\n"
#define CMND_HKEY9      "^B - перейти вниз экрана\n"
#define CMND_HKEY0      "^P or PGUP - промотать экран вверх\n"
#define CMND_HKEYA      "^N or PGDN - промотать экран вниз\n"
#ifdef  CHARSET
# define CMND_HKEYB     "^E - перекодировать строку ввода после курсора\n"
#endif  /* CHARSET */
#define CMND_HKEYC      "'`' , [1-9] - положить ник #[1-9] в строку ввода\n"
#define CMND_HKEYD      "'/' , [1-9] - послать сообщение нику #[1-9]\n"
#define CMND_VERSION    "[%s] %s v%s.\n"
#define CMND_STATUS     "[%s] текущий статус:\n"
#define CMND_STATUSA    "адр: %s, порт: %u, прот: %s\n"
#define CMND_STATUSL    "присоединенных клиентов: %d\n"
#define CMND_VERBOSEON  "[%s] комментарии включены.\n"
#define CMND_VERBOSEOFF "[%s] комментарии отключены.\n"
#define CMND_CLEAR      "[%s] канал очищен.\n"
#ifdef  SHELL
# define CMND_SHELL     "[%s] команда шелла:\n"
# define CMND_SHELLE    "[%s] выполнить команду неудалось.\n"
#else   /* SHELL */
# define CMND_SHELLD    "[%s] /! команда отключена.\n"
#endif  /* SHELL */
#define CMND_LOAD       "[%s] конфигурация загружена из:\n"
#define CMND_LOADF      "[%s] загрузка конфигурации не удалась.\n"
#define CMND_SAVE       "[%s] конфигурация сохранена в:\n"
#define CMND_SAVEF      "[%s] сохранение конфигурации не удалось.\n"
#define CMND_ANSDND     "[%s] автоответ режима Не Беспокоить:\n"
#define CMND_ANSAWAY    "[%s] автоответ режима Ушел:\n"
#define CMND_ANSOFF     "[%s] автоответ режима Отключен:\n"
#define CMND_GENDERM    "[%s] пол мужской.\n"
#define CMND_GENDERF    "[%s] пол женский.\n"
#define CMND_BEEPALL    "[%s] проигрывать все звуки.\n"
#define CMND_BEEPCUR    "[%s] проигрывать только текущие звуки.\n"
#define CMND_FAVORITEN  "[%s] выделенные ники:\n"
#define CMND_FAVORITEI  "[%s] ник %s выделен.\n"
#define CMND_FAVORITEU  "[%s] ник %s не выделен.\n"
#define CMND_IGNOREN    "[%s] игнорируемые ники:\n"
#define CMND_IGNOREI    "[%s] ник %s игнорируется.\n"
#define CMND_IGNOREU    "[%s] ник %s не игнорируется.\n"
#define CMND_BANA       "[%s] игнорируемые адреса:\n"
#define CMND_BANB       "[%s] адрес %s игнорируется.\n"
#define CMND_BANU       "[%s] адрес %s не игнорируется.\n"
#define CMND_INICK      "[%s] неправильный ник %s\n"
#define CMND_ICHANNEL   "[%s] неправильный канал %s\n"
#define CMND_LEAVE      "[%s] невозможно покинуть канал %s\n"
#define CMND_NICK       "[%s] ник %s уже есть.\n"
#define CMND_MESG       "[%s] сообщение для %s:\n"
#define CMND_MASS       "[%s] массовое сообщение:\n"
#define CMND_QTOPIC     "[%s] текущий топик:\n"
#define CMND_TOPIC      "[%s] текущий топик на %s:\n"
#define CMND_UNKNOWN    "[%s] неизвестная команда: %s\n"

#define ECHAT_SIGNAL    "[%s] получен SIGNAL %d, немедленный выход.\n"
#define ECHAT_BYE       "[%s] до свидания, %s.\n"
#define ECHAT_WELCOME   "[%s] добро пожаловать в %s v%s, %s.\n"

#define PARS_NICK       "[%s] %s сменил ник на %s.\n"
#define PARS_MESG       "[%s] сообщение от %s:\n"
#define PARS_MASS       "[%s] массовое сообщение от %s:\n"
#define PARS_MESGACK    "[%s] %s получил сообщение.\n"
#define PARS_MESGANS    "[%s] автоответ от %s:\n"
#define PARS_EXEC       "[%s] команда от %s:\n"
#define PARS_EXECACK    "[%s] результаты команды от %s:\n"
#define PARS_QTOPIC     "[%s] новый топик:\n"
#define PARS_TOPIC      "[%s] новый топик на %s:\n"
#define PARS_QTOPICC    "[%s] текущий топик:\n"
#define PARS_TOPICC     "[%s] текущий топик на %s:\n"
#define PARS_MODE       "[%s] %s вошел в режим "
#define PARS_MODENORMAL "Нормальный.\n"
#define PARS_MODEDND    "Не Беспокоить:\n"
#define PARS_MODEAWAY   "Ушел:\n"
#define PARS_MODEOFF    "Отключен:\n"
#define PARS_INFO       "[%s] запрос инфо от %s.\n"
#define PARS_INFORM     "[%s] инфо на %s:\n"
#define PARS_QINFOUH    "пользователь: %s, компьютер: %s [%s], память: %s\n"
#define PARS_INFOUH     "пользователь: %s, компьютер: %s [%s]\n"
#define PARS_INFOCH     "каналы: %s\n"
#define PARS_BEEP       "[%s] получен звук от %s.\n"
#define PARS_BEEPACK    "[%s] звук отправлен %s.\n"
#define PARS_HERE       "[%s] тут %s (%s).\n"
#define PARS_HEREACT    "активен"
#define PARS_HERENAC    "неактивен"

#define SOCK_ALLOC      "[%s] неудалось получить сокет.\n"
#define SOCK_ROUTE      "[%s] неудалось переслать пакет на %s\n"
#define SOCK_RECV       "[%s] неудалось принять пакет от %s\n"
#define SOCK_ADDRESS    "[%s] неправильный адрес для %s: %s\n"
#define SOCK_USEND      "[%s] неудалось отправить пакет на %s\n"
#define SOCK_BSEND      "[%s] неудалось отправить пакет на %s\n"

#define SOCK_TCONN      "[%s] клиент присоединился.\n"
#define SOCK_TWELCOME   "Welcome to eChat.\n"
#define SOCK_TOUT       "Out of clients.\n"

#define CMND_SCLEAR     "Канал очищен."
#define CMND_SLOAD      "Конфигурация загружена."
#define CMND_SLOADF     "Загрузка конфигурации не удалась."
#define CMND_SSAVE      "Конфигурация сохранена."
#define CMND_SSAVEF     "Сохранение конфигурации не удалось."
#define CMND_SGENDERM   "Пол мужской."
#define CMND_SGENDERF   "Пол женский."
#define CMND_SBEEPALL   "Проигрывать все звуки."
#define CMND_SBEEPCUR   "Проигрывать только текущие звуки."
#define CMND_SUNKNOWN   "Неизвестная команда."

#define TERM_SQUIT      "Выход."

#define MAKE_SCHAT      "Строка чата отправлена."
#define MAKE_SNICK      "Ник сменен."
#define MAKE_SMESG      "Сообщение отправлено."
#define MAKE_SMASS      "Массовое сообщение отправлено."
#define MAKE_SME        "Действие отправлено."
#define MAKE_STOPIC     "Новый топик отправлен."
#define MAKE_SMODE      "Режим сменен."
#define MAKE_SINFO      "Инфо отправлена."
#define MAKE_SBEEP      "Сигнал отправлен."
#define MAKE_SPRIVJOIN  "Приват запущен."
#define MAKE_SPRIVLEAVE "Приват закрыт."
#define MAKE_SPRIVCHAT  "Строка привата отправлена."
#define MAKE_SPRIVME    "Действие привата отправлено."
#define MAKE_SHERE      "Запрос кто тут отправлен."
#define MAKE_SACTIVE    "Активность сменена."

#define PARS_SHERE      "Запрос кто тут получен."
#define PARS_SBEEPREQ   "Запрос \"beepreq\" получен."

#define SOCK_SROUTE     "Пересылка пакета неудалась."
#define SOCK_SRECEIVE   "Прием пакета неудался."
#define SOCK_SUSEND     "Отправка пакета неудалась."
#define SOCK_SBSEND     "Отправка пакета неудалась."

#endif  /* _MESG_H */
