#!/bin/bash

# source application-specific settings
[ -f /etc/conf.d/httpd ] && . /etc/conf.d/httpd

# general config
. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
    stat_busy "Starting HTTP Daemon"
		if [ "$HTTPD_USE_SSL" = "yes" -o "$HTTPD_USE_SSL" = "YES" ]; then
      /usr/sbin/apachectl startssl &>/dev/null
		else
      /usr/sbin/apachectl start &>/dev/null
		fi
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon httpd
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping HTTP Daemon"
    /usr/sbin/apachectl stop &>/dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon httpd
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 3
    $0 start
    ;;
  reload)
    if [ -f /var/run/httpd.pid ]; then
      status "Reloading HTTP Configuration" kill -HUP `cat /var/run/httpd.pid`
    fi
    ;;
  *)
    echo "usage: $0 {start|stop|restart|reload}"  
esac
