# Makefile.in generated automatically by automake 1.5 from Makefile.am.

# Copyright 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001
# Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



SHELL = /bin/sh

srcdir = .
top_srcdir = ..

prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include
pkgdatadir = $(datadir)/tvision
pkglibdir = $(libdir)/tvision
pkgincludedir = $(includedir)/tvision
top_builddir = ..

ACLOCAL = ${SHELL} /home/sergej/aur/tvision2/tvision-0.8/missing --run aclocal
AUTOCONF = ${SHELL} /home/sergej/aur/tvision2/tvision-0.8/missing --run autoconf
AUTOMAKE = ${SHELL} /home/sergej/aur/tvision2/tvision-0.8/missing --run automake
AUTOHEADER = ${SHELL} /home/sergej/aur/tvision2/tvision-0.8/missing --run autoheader

INSTALL = /bin/install -c
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
INSTALL_HEADER = $(INSTALL_DATA)
transform = s,x,x,
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_alias = 
host_triplet = i686-pc-linux-gnu
AMTAR = ${SHELL} /home/sergej/aur/tvision2/tvision-0.8/missing --run tar
AS = @AS@
AWK = gawk
CC = gcc
CPP = gcc -E
CXX = g++
DEPDIR = .deps
DLLTOOL = @DLLTOOL@
ECHO = echo
EXEEXT = 
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = tvision
RANLIB = ranlib
STRIP = strip
VERSION = 0.8
am__include = include
am__quote = 
install_sh = /home/sergej/aur/tvision2/tvision-0.8/install-sh

AUTOMAKE_OPTIONS = foreign

CLEANFILES = tvision

pkginclude_HEADERS = \
app.h buffers.h colorsel.h dialogs.h drawbuf.h editors.h \
help.h helpbase.h menus.h msgbox.h objects.h outline.h resource.h \
stddlg.h system.h textview.h tkeys.h tobjstrm.h ttypes.h tv.h \
tvconfig.h tvobjs.h util.h validate.h views.h


lib_LIBRARIES = libtvision.a
lib_LTLIBRARIES = libtvision.la
libtvision_la_LDFLAGS = -version-info 0:7:0

INCLUDES = -I..

libtvision_a_SOURCES = TApplication.cc TBackground.cc TButton.cc \
TChDirDialog.cc TCheckBoxes.cc \
TCluster.cc TCollection.cc TCommandSet.cc TDeskTop.cc TDialog.cc \
TDirCollection.cc TDirListBox.cc TEditWindow.cc TEditor.cc \
TFileCollection.cc TFileDialog.cc TFileEditor.cc TFileList.cc TFrame.cc \
TGroup.cc THistory.cc THistoryViewer.cc THistoryWindow.cc TIndicator.cc \
TInputLine.cc TLabel.cc TListBox.cc TListViewer.cc TMemo.cc TMenuBar.cc \
TMenuBox.cc TMenuPopup.cc TMenuView.cc TMultiCheckBoxes.cc TObject.cc \
TOutline.cc TParamText.cc TPoint.cc TProgram.cc TRadioButtons.cc \
TResourceCollection.cc TResourceFile.cc TScrollBar.cc TScroller.cc \
TSortedCollection.cc TStaticText.cc TStatusLine.cc TStrListMaker.cc \
TStringCollection.cc TValidator.cc TView.cc TWindow.cc allnames.cc asm.cc \
colorsel.cc drivers.cc editstat.cc help.cc helpbase.cc histlist.cc menu.cc \
misc.cc msgbox.cc new.cc palette.cc sall.cc stddlg.cc system.cc textview.cc \
tobjstrm.cc tvtext.cc


libtvision_la_SOURCES = tvision TApplication.cc TBackground.cc TButton.cc \
TChDirDialog.cc TCheckBoxes.cc \
TCluster.cc TCollection.cc TCommandSet.cc TDeskTop.cc TDialog.cc \
TDirCollection.cc TDirListBox.cc TEditWindow.cc TEditor.cc \
TFileCollection.cc TFileDialog.cc TFileEditor.cc TFileList.cc TFrame.cc \
TGroup.cc THistory.cc THistoryViewer.cc THistoryWindow.cc TIndicator.cc \
TInputLine.cc TLabel.cc TListBox.cc TListViewer.cc TMemo.cc TMenuBar.cc \
TMenuBox.cc TMenuPopup.cc TMenuView.cc TMultiCheckBoxes.cc TObject.cc \
TOutline.cc TParamText.cc TPoint.cc TProgram.cc TRadioButtons.cc \
TResourceCollection.cc TResourceFile.cc TScrollBar.cc TScroller.cc \
TSortedCollection.cc TStaticText.cc TStatusLine.cc TStrListMaker.cc \
TStringCollection.cc TValidator.cc TView.cc TWindow.cc allnames.cc asm.cc \
colorsel.cc drivers.cc editstat.cc help.cc helpbase.cc histlist.cc menu.cc \
misc.cc msgbox.cc new.cc palette.cc sall.cc stddlg.cc system.cc textview.cc \
tobjstrm.cc tvtext.cc

subdir = lib
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = $(top_builddir)/config.h
CONFIG_CLEAN_FILES =
LIBRARIES = $(lib_LIBRARIES)

libtvision_a_AR = $(AR) cru
libtvision_a_LIBADD =
am_libtvision_a_OBJECTS = TApplication.$(OBJEXT) TBackground.$(OBJEXT) \
	TButton.$(OBJEXT) TChDirDialog.$(OBJEXT) TCheckBoxes.$(OBJEXT) \
	TCluster.$(OBJEXT) TCollection.$(OBJEXT) TCommandSet.$(OBJEXT) \
	TDeskTop.$(OBJEXT) TDialog.$(OBJEXT) TDirCollection.$(OBJEXT) \
	TDirListBox.$(OBJEXT) TEditWindow.$(OBJEXT) TEditor.$(OBJEXT) \
	TFileCollection.$(OBJEXT) TFileDialog.$(OBJEXT) \
	TFileEditor.$(OBJEXT) TFileList.$(OBJEXT) TFrame.$(OBJEXT) \
	TGroup.$(OBJEXT) THistory.$(OBJEXT) THistoryViewer.$(OBJEXT) \
	THistoryWindow.$(OBJEXT) TIndicator.$(OBJEXT) \
	TInputLine.$(OBJEXT) TLabel.$(OBJEXT) TListBox.$(OBJEXT) \
	TListViewer.$(OBJEXT) TMemo.$(OBJEXT) TMenuBar.$(OBJEXT) \
	TMenuBox.$(OBJEXT) TMenuPopup.$(OBJEXT) TMenuView.$(OBJEXT) \
	TMultiCheckBoxes.$(OBJEXT) TObject.$(OBJEXT) TOutline.$(OBJEXT) \
	TParamText.$(OBJEXT) TPoint.$(OBJEXT) TProgram.$(OBJEXT) \
	TRadioButtons.$(OBJEXT) TResourceCollection.$(OBJEXT) \
	TResourceFile.$(OBJEXT) TScrollBar.$(OBJEXT) \
	TScroller.$(OBJEXT) TSortedCollection.$(OBJEXT) \
	TStaticText.$(OBJEXT) TStatusLine.$(OBJEXT) \
	TStrListMaker.$(OBJEXT) TStringCollection.$(OBJEXT) \
	TValidator.$(OBJEXT) TView.$(OBJEXT) TWindow.$(OBJEXT) \
	allnames.$(OBJEXT) asm.$(OBJEXT) colorsel.$(OBJEXT) \
	drivers.$(OBJEXT) editstat.$(OBJEXT) help.$(OBJEXT) \
	helpbase.$(OBJEXT) histlist.$(OBJEXT) menu.$(OBJEXT) \
	misc.$(OBJEXT) msgbox.$(OBJEXT) new.$(OBJEXT) palette.$(OBJEXT) \
	sall.$(OBJEXT) stddlg.$(OBJEXT) system.$(OBJEXT) \
	textview.$(OBJEXT) tobjstrm.$(OBJEXT) tvtext.$(OBJEXT)
libtvision_a_OBJECTS = $(am_libtvision_a_OBJECTS)
LTLIBRARIES = $(lib_LTLIBRARIES)

libtvision_la_LIBADD =
am_libtvision_la_OBJECTS = TApplication.lo TBackground.lo TButton.lo \
	TChDirDialog.lo TCheckBoxes.lo TCluster.lo TCollection.lo \
	TCommandSet.lo TDeskTop.lo TDialog.lo TDirCollection.lo \
	TDirListBox.lo TEditWindow.lo TEditor.lo TFileCollection.lo \
	TFileDialog.lo TFileEditor.lo TFileList.lo TFrame.lo TGroup.lo \
	THistory.lo THistoryViewer.lo THistoryWindow.lo TIndicator.lo \
	TInputLine.lo TLabel.lo TListBox.lo TListViewer.lo TMemo.lo \
	TMenuBar.lo TMenuBox.lo TMenuPopup.lo TMenuView.lo \
	TMultiCheckBoxes.lo TObject.lo TOutline.lo TParamText.lo \
	TPoint.lo TProgram.lo TRadioButtons.lo TResourceCollection.lo \
	TResourceFile.lo TScrollBar.lo TScroller.lo \
	TSortedCollection.lo TStaticText.lo TStatusLine.lo \
	TStrListMaker.lo TStringCollection.lo TValidator.lo TView.lo \
	TWindow.lo allnames.lo asm.lo colorsel.lo drivers.lo \
	editstat.lo help.lo helpbase.lo histlist.lo menu.lo misc.lo \
	msgbox.lo new.lo palette.lo sall.lo stddlg.lo system.lo \
	textview.lo tobjstrm.lo tvtext.lo
libtvision_la_OBJECTS = $(am_libtvision_la_OBJECTS)

DEFS = -DHAVE_CONFIG_H
DEFAULT_INCLUDES =  -I. -I$(srcdir) -I$(top_builddir)
CPPFLAGS = 
LDFLAGS = 
LIBS = -lgpm -lncurses 
depcomp = $(SHELL) $(top_srcdir)/depcomp
DEP_FILES = $(DEPDIR)/TApplication.Plo \
	$(DEPDIR)/TApplication.Po $(DEPDIR)/TBackground.Plo \
	$(DEPDIR)/TBackground.Po $(DEPDIR)/TButton.Plo \
	$(DEPDIR)/TButton.Po $(DEPDIR)/TChDirDialog.Plo \
	$(DEPDIR)/TChDirDialog.Po $(DEPDIR)/TCheckBoxes.Plo \
	$(DEPDIR)/TCheckBoxes.Po $(DEPDIR)/TCluster.Plo \
	$(DEPDIR)/TCluster.Po $(DEPDIR)/TCollection.Plo \
	$(DEPDIR)/TCollection.Po $(DEPDIR)/TCommandSet.Plo \
	$(DEPDIR)/TCommandSet.Po $(DEPDIR)/TDeskTop.Plo \
	$(DEPDIR)/TDeskTop.Po $(DEPDIR)/TDialog.Plo \
	$(DEPDIR)/TDialog.Po $(DEPDIR)/TDirCollection.Plo \
	$(DEPDIR)/TDirCollection.Po \
	$(DEPDIR)/TDirListBox.Plo $(DEPDIR)/TDirListBox.Po \
	$(DEPDIR)/TEditWindow.Plo $(DEPDIR)/TEditWindow.Po \
	$(DEPDIR)/TEditor.Plo $(DEPDIR)/TEditor.Po \
	$(DEPDIR)/TFileCollection.Plo \
	$(DEPDIR)/TFileCollection.Po \
	$(DEPDIR)/TFileDialog.Plo $(DEPDIR)/TFileDialog.Po \
	$(DEPDIR)/TFileEditor.Plo $(DEPDIR)/TFileEditor.Po \
	$(DEPDIR)/TFileList.Plo $(DEPDIR)/TFileList.Po \
	$(DEPDIR)/TFrame.Plo $(DEPDIR)/TFrame.Po \
	$(DEPDIR)/TGroup.Plo $(DEPDIR)/TGroup.Po \
	$(DEPDIR)/THistory.Plo $(DEPDIR)/THistory.Po \
	$(DEPDIR)/THistoryViewer.Plo \
	$(DEPDIR)/THistoryViewer.Po \
	$(DEPDIR)/THistoryWindow.Plo \
	$(DEPDIR)/THistoryWindow.Po \
	$(DEPDIR)/TIndicator.Plo $(DEPDIR)/TIndicator.Po \
	$(DEPDIR)/TInputLine.Plo $(DEPDIR)/TInputLine.Po \
	$(DEPDIR)/TLabel.Plo $(DEPDIR)/TLabel.Po \
	$(DEPDIR)/TListBox.Plo $(DEPDIR)/TListBox.Po \
	$(DEPDIR)/TListViewer.Plo $(DEPDIR)/TListViewer.Po \
	$(DEPDIR)/TMemo.Plo $(DEPDIR)/TMemo.Po \
	$(DEPDIR)/TMenuBar.Plo $(DEPDIR)/TMenuBar.Po \
	$(DEPDIR)/TMenuBox.Plo $(DEPDIR)/TMenuBox.Po \
	$(DEPDIR)/TMenuPopup.Plo $(DEPDIR)/TMenuPopup.Po \
	$(DEPDIR)/TMenuView.Plo $(DEPDIR)/TMenuView.Po \
	$(DEPDIR)/TMultiCheckBoxes.Plo \
	$(DEPDIR)/TMultiCheckBoxes.Po $(DEPDIR)/TObject.Plo \
	$(DEPDIR)/TObject.Po $(DEPDIR)/TOutline.Plo \
	$(DEPDIR)/TOutline.Po $(DEPDIR)/TParamText.Plo \
	$(DEPDIR)/TParamText.Po $(DEPDIR)/TPoint.Plo \
	$(DEPDIR)/TPoint.Po $(DEPDIR)/TProgram.Plo \
	$(DEPDIR)/TProgram.Po $(DEPDIR)/TRadioButtons.Plo \
	$(DEPDIR)/TRadioButtons.Po \
	$(DEPDIR)/TResourceCollection.Plo \
	$(DEPDIR)/TResourceCollection.Po \
	$(DEPDIR)/TResourceFile.Plo \
	$(DEPDIR)/TResourceFile.Po $(DEPDIR)/TScrollBar.Plo \
	$(DEPDIR)/TScrollBar.Po $(DEPDIR)/TScroller.Plo \
	$(DEPDIR)/TScroller.Po \
	$(DEPDIR)/TSortedCollection.Plo \
	$(DEPDIR)/TSortedCollection.Po \
	$(DEPDIR)/TStaticText.Plo $(DEPDIR)/TStaticText.Po \
	$(DEPDIR)/TStatusLine.Plo $(DEPDIR)/TStatusLine.Po \
	$(DEPDIR)/TStrListMaker.Plo \
	$(DEPDIR)/TStrListMaker.Po \
	$(DEPDIR)/TStringCollection.Plo \
	$(DEPDIR)/TStringCollection.Po \
	$(DEPDIR)/TValidator.Plo $(DEPDIR)/TValidator.Po \
	$(DEPDIR)/TView.Plo $(DEPDIR)/TView.Po \
	$(DEPDIR)/TWindow.Plo $(DEPDIR)/TWindow.Po \
	$(DEPDIR)/allnames.Plo $(DEPDIR)/allnames.Po \
	$(DEPDIR)/asm.Plo $(DEPDIR)/asm.Po \
	$(DEPDIR)/colorsel.Plo $(DEPDIR)/colorsel.Po \
	$(DEPDIR)/drivers.Plo $(DEPDIR)/drivers.Po \
	$(DEPDIR)/editstat.Plo $(DEPDIR)/editstat.Po \
	$(DEPDIR)/help.Plo $(DEPDIR)/help.Po \
	$(DEPDIR)/helpbase.Plo $(DEPDIR)/helpbase.Po \
	$(DEPDIR)/histlist.Plo $(DEPDIR)/histlist.Po \
	$(DEPDIR)/menu.Plo $(DEPDIR)/menu.Po \
	$(DEPDIR)/misc.Plo $(DEPDIR)/misc.Po \
	$(DEPDIR)/msgbox.Plo $(DEPDIR)/msgbox.Po \
	$(DEPDIR)/new.Plo $(DEPDIR)/new.Po \
	$(DEPDIR)/palette.Plo $(DEPDIR)/palette.Po \
	$(DEPDIR)/sall.Plo $(DEPDIR)/sall.Po \
	$(DEPDIR)/stddlg.Plo $(DEPDIR)/stddlg.Po \
	$(DEPDIR)/system.Plo $(DEPDIR)/system.Po \
	$(DEPDIR)/textview.Plo $(DEPDIR)/textview.Po \
	$(DEPDIR)/tobjstrm.Plo $(DEPDIR)/tobjstrm.Po \
	$(DEPDIR)/tvtext.Plo $(DEPDIR)/tvtext.Po
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) --mode=compile $(CXX) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) --mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
CXXFLAGS = -g -O2
DIST_SOURCES = $(libtvision_a_SOURCES) $(libtvision_la_SOURCES)
HEADERS = $(pkginclude_HEADERS)

DIST_COMMON = $(pkginclude_HEADERS) Makefile.am Makefile.in
SOURCES = $(libtvision_a_SOURCES) $(libtvision_la_SOURCES)

all: all-am

.SUFFIXES:
.SUFFIXES: .cc .lo .o .obj

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool
$(srcdir)/Makefile.in:  Makefile.am  $(top_srcdir)/configure.in $(ACLOCAL_M4)
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --foreign  lib/Makefile

AR = ar
install-libLIBRARIES: $(lib_LIBRARIES)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(libdir)
	@list='$(lib_LIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo " $(INSTALL_DATA) $$p $(DESTDIR)$(libdir)/$$p"; \
	    $(INSTALL_DATA) $$p $(DESTDIR)$(libdir)/$$p; \
	  else :; fi; \
	done
	@$(POST_INSTALL)
	@list='$(lib_LIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo " $(RANLIB) $(DESTDIR)$(libdir)/$$p"; \
	    $(RANLIB) $(DESTDIR)$(libdir)/$$p; \
	  else :; fi; \
	done

uninstall-libLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LIBRARIES)'; for p in $$list; do \
	  echo " rm -f $(DESTDIR)$(libdir)/$$p"; \
	  rm -f $(DESTDIR)$(libdir)/$$p; \
	done

clean-libLIBRARIES:
	-test -z "$(lib_LIBRARIES)" || rm -f $(lib_LIBRARIES)
libtvision.a: $(libtvision_a_OBJECTS) $(libtvision_a_DEPENDENCIES) 
	-rm -f libtvision.a
	$(libtvision_a_AR) libtvision.a $(libtvision_a_OBJECTS) $(libtvision_a_LIBADD)
	$(RANLIB) libtvision.a
install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(libdir)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo " $(LIBTOOL) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$p $(DESTDIR)$(libdir)/$$p"; \
	    $(LIBTOOL) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$p $(DESTDIR)$(libdir)/$$p; \
	  else :; fi; \
	done

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  echo " $(LIBTOOL) --mode=uninstall rm -f $(DESTDIR)$(libdir)/$$p"; \
	  $(LIBTOOL) --mode=uninstall rm -f $(DESTDIR)$(libdir)/$$p; \
	done

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)
libtvision.la: $(libtvision_la_OBJECTS) $(libtvision_la_DEPENDENCIES) 
	$(CXXLINK) -rpath $(libdir) $(libtvision_la_LDFLAGS) $(libtvision_la_OBJECTS) $(libtvision_la_LIBADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT) core *.core

distclean-compile:
	-rm -f *.tab.c

include $(DEPDIR)/TApplication.Plo
include $(DEPDIR)/TApplication.Po
include $(DEPDIR)/TBackground.Plo
include $(DEPDIR)/TBackground.Po
include $(DEPDIR)/TButton.Plo
include $(DEPDIR)/TButton.Po
include $(DEPDIR)/TChDirDialog.Plo
include $(DEPDIR)/TChDirDialog.Po
include $(DEPDIR)/TCheckBoxes.Plo
include $(DEPDIR)/TCheckBoxes.Po
include $(DEPDIR)/TCluster.Plo
include $(DEPDIR)/TCluster.Po
include $(DEPDIR)/TCollection.Plo
include $(DEPDIR)/TCollection.Po
include $(DEPDIR)/TCommandSet.Plo
include $(DEPDIR)/TCommandSet.Po
include $(DEPDIR)/TDeskTop.Plo
include $(DEPDIR)/TDeskTop.Po
include $(DEPDIR)/TDialog.Plo
include $(DEPDIR)/TDialog.Po
include $(DEPDIR)/TDirCollection.Plo
include $(DEPDIR)/TDirCollection.Po
include $(DEPDIR)/TDirListBox.Plo
include $(DEPDIR)/TDirListBox.Po
include $(DEPDIR)/TEditWindow.Plo
include $(DEPDIR)/TEditWindow.Po
include $(DEPDIR)/TEditor.Plo
include $(DEPDIR)/TEditor.Po
include $(DEPDIR)/TFileCollection.Plo
include $(DEPDIR)/TFileCollection.Po
include $(DEPDIR)/TFileDialog.Plo
include $(DEPDIR)/TFileDialog.Po
include $(DEPDIR)/TFileEditor.Plo
include $(DEPDIR)/TFileEditor.Po
include $(DEPDIR)/TFileList.Plo
include $(DEPDIR)/TFileList.Po
include $(DEPDIR)/TFrame.Plo
include $(DEPDIR)/TFrame.Po
include $(DEPDIR)/TGroup.Plo
include $(DEPDIR)/TGroup.Po
include $(DEPDIR)/THistory.Plo
include $(DEPDIR)/THistory.Po
include $(DEPDIR)/THistoryViewer.Plo
include $(DEPDIR)/THistoryViewer.Po
include $(DEPDIR)/THistoryWindow.Plo
include $(DEPDIR)/THistoryWindow.Po
include $(DEPDIR)/TIndicator.Plo
include $(DEPDIR)/TIndicator.Po
include $(DEPDIR)/TInputLine.Plo
include $(DEPDIR)/TInputLine.Po
include $(DEPDIR)/TLabel.Plo
include $(DEPDIR)/TLabel.Po
include $(DEPDIR)/TListBox.Plo
include $(DEPDIR)/TListBox.Po
include $(DEPDIR)/TListViewer.Plo
include $(DEPDIR)/TListViewer.Po
include $(DEPDIR)/TMemo.Plo
include $(DEPDIR)/TMemo.Po
include $(DEPDIR)/TMenuBar.Plo
include $(DEPDIR)/TMenuBar.Po
include $(DEPDIR)/TMenuBox.Plo
include $(DEPDIR)/TMenuBox.Po
include $(DEPDIR)/TMenuPopup.Plo
include $(DEPDIR)/TMenuPopup.Po
include $(DEPDIR)/TMenuView.Plo
include $(DEPDIR)/TMenuView.Po
include $(DEPDIR)/TMultiCheckBoxes.Plo
include $(DEPDIR)/TMultiCheckBoxes.Po
include $(DEPDIR)/TObject.Plo
include $(DEPDIR)/TObject.Po
include $(DEPDIR)/TOutline.Plo
include $(DEPDIR)/TOutline.Po
include $(DEPDIR)/TParamText.Plo
include $(DEPDIR)/TParamText.Po
include $(DEPDIR)/TPoint.Plo
include $(DEPDIR)/TPoint.Po
include $(DEPDIR)/TProgram.Plo
include $(DEPDIR)/TProgram.Po
include $(DEPDIR)/TRadioButtons.Plo
include $(DEPDIR)/TRadioButtons.Po
include $(DEPDIR)/TResourceCollection.Plo
include $(DEPDIR)/TResourceCollection.Po
include $(DEPDIR)/TResourceFile.Plo
include $(DEPDIR)/TResourceFile.Po
include $(DEPDIR)/TScrollBar.Plo
include $(DEPDIR)/TScrollBar.Po
include $(DEPDIR)/TScroller.Plo
include $(DEPDIR)/TScroller.Po
include $(DEPDIR)/TSortedCollection.Plo
include $(DEPDIR)/TSortedCollection.Po
include $(DEPDIR)/TStaticText.Plo
include $(DEPDIR)/TStaticText.Po
include $(DEPDIR)/TStatusLine.Plo
include $(DEPDIR)/TStatusLine.Po
include $(DEPDIR)/TStrListMaker.Plo
include $(DEPDIR)/TStrListMaker.Po
include $(DEPDIR)/TStringCollection.Plo
include $(DEPDIR)/TStringCollection.Po
include $(DEPDIR)/TValidator.Plo
include $(DEPDIR)/TValidator.Po
include $(DEPDIR)/TView.Plo
include $(DEPDIR)/TView.Po
include $(DEPDIR)/TWindow.Plo
include $(DEPDIR)/TWindow.Po
include $(DEPDIR)/allnames.Plo
include $(DEPDIR)/allnames.Po
include $(DEPDIR)/asm.Plo
include $(DEPDIR)/asm.Po
include $(DEPDIR)/colorsel.Plo
include $(DEPDIR)/colorsel.Po
include $(DEPDIR)/drivers.Plo
include $(DEPDIR)/drivers.Po
include $(DEPDIR)/editstat.Plo
include $(DEPDIR)/editstat.Po
include $(DEPDIR)/help.Plo
include $(DEPDIR)/help.Po
include $(DEPDIR)/helpbase.Plo
include $(DEPDIR)/helpbase.Po
include $(DEPDIR)/histlist.Plo
include $(DEPDIR)/histlist.Po
include $(DEPDIR)/menu.Plo
include $(DEPDIR)/menu.Po
include $(DEPDIR)/misc.Plo
include $(DEPDIR)/misc.Po
include $(DEPDIR)/msgbox.Plo
include $(DEPDIR)/msgbox.Po
include $(DEPDIR)/new.Plo
include $(DEPDIR)/new.Po
include $(DEPDIR)/palette.Plo
include $(DEPDIR)/palette.Po
include $(DEPDIR)/sall.Plo
include $(DEPDIR)/sall.Po
include $(DEPDIR)/stddlg.Plo
include $(DEPDIR)/stddlg.Po
include $(DEPDIR)/system.Plo
include $(DEPDIR)/system.Po
include $(DEPDIR)/textview.Plo
include $(DEPDIR)/textview.Po
include $(DEPDIR)/tobjstrm.Plo
include $(DEPDIR)/tobjstrm.Po
include $(DEPDIR)/tvtext.Plo
include $(DEPDIR)/tvtext.Po

distclean-depend:
	-rm -rf $(DEPDIR)

.cc.o:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXXCOMPILE) -c -o $@ `test -f $< || echo '$(srcdir)/'`$<

.cc.obj:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXXCOMPILE) -c -o $@ `cygpath -w $<`

.cc.lo:
	source='$<' object='$@' libtool=yes \
	depfile='$(DEPDIR)/$*.Plo' tmpdepfile='$(DEPDIR)/$*.TPlo' \
	$(CXXDEPMODE) $(depcomp) \
	$(LTCXXCOMPILE) -c -o $@ `test -f $< || echo '$(srcdir)/'`$<
CXXDEPMODE = depmode=gcc3
uninstall-info-am:
install-pkgincludeHEADERS: $(pkginclude_HEADERS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(pkgincludedir)
	@list='$(pkginclude_HEADERS)'; for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  f="`echo $$p | sed -e 's|^.*/||'`"; \
	  echo " $(INSTALL_HEADER) $$d$$p $(DESTDIR)$(pkgincludedir)/$$f"; \
	  $(INSTALL_HEADER) $$d$$p $(DESTDIR)$(pkgincludedir)/$$f; \
	done

uninstall-pkgincludeHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(pkginclude_HEADERS)'; for p in $$list; do \
	  f="`echo $$p | sed -e 's|^.*/||'`"; \
	  echo " rm -f $(DESTDIR)$(pkgincludedir)/$$f"; \
	  rm -f $(DESTDIR)$(pkgincludedir)/$$f; \
	done

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || etags $(ETAGS_ARGS) $$tags  $$unique $(LISP)

GTAGS:
	here=`CDPATH=: && cd $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH

DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)

top_distdir = ..
distdir = $(top_distdir)/$(PACKAGE)-$(VERSION)

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  if test -f $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    $(mkinstalldirs) "$(distdir)/$$dir"; \
	  fi; \
	  if test -d $$d/$$file; then \
	    cp -pR $$d/$$file $(distdir) \
	    || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(LIBRARIES) $(LTLIBRARIES) $(HEADERS)

installdirs:
	$(mkinstalldirs) $(DESTDIR)$(libdir) $(DESTDIR)$(libdir) $(DESTDIR)$(pkgincludedir)

install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES) stamp-h stamp-h[0-9]*

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-generic clean-libLIBRARIES clean-libLTLIBRARIES \
	clean-libtool mostlyclean-am

distclean: distclean-am

distclean-am: clean-am distclean-compile distclean-depend \
	distclean-generic distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

info: info-am

info-am:

install-data-am: install-pkgincludeHEADERS

install-exec-am: install-libLIBRARIES install-libLTLIBRARIES

install-info: install-info-am

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-am

maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

uninstall-am: uninstall-info-am uninstall-libLIBRARIES \
	uninstall-libLTLIBRARIES uninstall-pkgincludeHEADERS

.PHONY: GTAGS all all-am check check-am clean clean-generic \
	clean-libLIBRARIES clean-libLTLIBRARIES clean-libtool distclean \
	distclean-compile distclean-depend distclean-generic \
	distclean-libtool distclean-tags distdir dvi dvi-am info \
	info-am install install-am install-data install-data-am \
	install-exec install-exec-am install-info install-info-am \
	install-libLIBRARIES install-libLTLIBRARIES install-man \
	install-pkgincludeHEADERS install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool tags uninstall \
	uninstall-am uninstall-info-am uninstall-libLIBRARIES \
	uninstall-libLTLIBRARIES uninstall-pkgincludeHEADERS


# Hack to create a symbolic link `tvision' pointing to this directory.
# This is needed because the sources contain directives like:
#     #include <tvision/tv.h>
# so the `tvision' directory must exist.

Makefile: tvision

tvision:
	ln -s $(srcdir)/. tvision
# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
